config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  post 'users/interests', to: 'users#interests'
  post 'users/goals', to: 'users#goals'

  resources :users do
    member do
      post 'follow'
      post 'unfollow'
      get 'user_goals'
      get 'user_follows'
    end
  end

  resources :interests
  resources :goals
  
  resources :posts do
    resources :comments
  end

  root 'home#index'

  get 'explore' => 'home#explore'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy 
  has_many :comments, dependent: :destroy
  has_many :relationships, foreign_key: :follower_id, dependent: :destroy
  has_many :followeds, through: :relationships
  has_many :reverse_relationships, foreign_key: :followed_id, class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :goals, dependent: :destroy
  has_many :user_interests
  has_many :interests, :through => :user_interests

  accepts_nested_attributes_for :user_interests, :allow_destroy => true

  validates_presence_of :fname, :lname, :bio, :location

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "120x120>" }, :default_url => "/images/thumb/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :set_user, only: [:show, :user_goals, :user_follows, :follow, :unfollow]

  def follow
    @relationship = Relationship.new(follower_id: current_user.id, followed_id: @user.id)
    if @relationship.save
      flash[:notice] = "Followed!"
      redirect_to @user
    else
      flash[:alert] = "Could not follow"
      redirect_to @user
    end
  end

  def unfollow
    @relationship = Relationship.where(follower_id: current_user.id, followed_id: @user.id).first
    if @relationship and @relationship.destroy
      flash[:notice] = "Unfollowed!"
      redirect_to @user
    else
      flash[:alert] = "Could not unfollow"
      redirect_to @user
    end
  end

  def index
    @users = User.first(20)
    @posts = Post.first(20)
    @posts = Post.order('created_at ASC')
  end

  def show
    @post = Post.new
    @comment = Comment.new
    @goal = Goal.new
  end

  def user_goals
    @goal = Goal.new
  end

  def user_follows
  end

  def new
    @user = User.new
    @post = Post.new
    @comment = Comment.new
  end

  def interests
    @interests = Interest.find(params[:interests])
    @interests.each do |interest|
      UserInterest.create(user_id: current_user.id, interest_id: interest.id)
    end
    redirect_to new_goal_path
  end


  private

  def set_user
		@user = User.find(params[:id])
	end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_bio.html.erb
<div class="row profile-bio">
	<div class="profile-pic"><%= image_tag @user.avatar.url(:thumb), class: "profile-image" %></div>
	<div class="user-info">	
		<h1 class="user_name"><%= @user.fname + " " + @user.lname %></h1>
		<p class="location"><%= @user.location %></p>
		<% if current_user and @user != current_user %>
			<% if current_user.followeds.include? @user %>
				<p><%= link_to 'Unfollow', unfollow_user_path(@user), method: :post %></p>
			<% else %>
				<p><%= link_to 'Follow', follow_user_path(@user),method: :post %></p>
			<% end %>
		<% end %>
		<% if current_user and @user == current_user %>
			<p><%= link_to 'Edit Profile', edit_user_registration_path %></p>
		<% end %>
	</div>
</div>
<div class="row user-bio">
	<p><%= @user.bio %></p>
</div>

app/views/users/_follow.html.erb
<div class="follow">	
	<h4> Following </h4>
	<ul>
		<% @user.followeds.each do |user| %>
			<li><%= image_tag user.avatar.url, class: "follow-avatar" %></li>
			<li><%= link_to user.fname + " " + user.lname, user_path(user) %></li><br>
		<% end %>
	</ul>
</div>
<hr class="follow-hr">
<div class="follow">
	<h4> Followers </h4>
	<ul>
		<% @user.followers.each do |user| %>
			<li><%= image_tag user.avatar.url, class: "follow-avatar" %></li>
			<li><%= link_to user.fname + " " + user.lname, user_path(user) %></li><br>
		<% end %>
	</ul>
</div>

app/views/users/_goal.html.erb
<ul class="user-goals-list">
	<% @user.goals.each do |goal| %>
		<li class="goal-body"><%= goal.body %></li>
		<li class="goal-created">Start Date: <%= goal.created_at.strftime("%m/%d/%Y") %></li>
		<li class="goal-timeline">Timeline: <%= display_timeline(goal) %></li>
		<li class="edit_user_goal">
			<% if current_user and @user == current_user %>
				<p class="edit-goal-link"><a href="#" class="update-progress">Update Progress</a> | <%= link_to 'Edit Goal', edit_goal_path(goal) %></p>
			<% end %>
		</li>
		<hr>
	<% end %>
</ul>

<% if current_user and @user == current_user %>
	<div class="add-goals">
		<a href="#"><span class="plus">+</span><p class="add-goal-btn">Add a Goal</p></a>
		<div class="row user-goals-form">	
			<%= form_for @goal do |f| %>
				<% if @goal.errors.any? %>
					<ul>
						<% @goal.errors.full_messages.each do |message| %>
							<li><%= message %></li>  
						<% end %>
					</ul>
				<% end %>

				<%= f.text_area :body, placeholder: "What is your goal...", class: "form-control goal-body-input" %>
				<%= f.label :timeline, class: "form-label" %>
				<%= f.select(:timeline, options_for_select([['Choose One', 0],['Day', 1],['Week', 2],['Month', 3],['Year', 4]])) %>
				<p class="skip-goal"><%= link_to 'Skip', user_goals_user_path(current_user) %></p>
				<%= f.submit 'Save', class: "btn btn-default goalsBtn" %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/users/_post.html.erb
<%= image_tag @user.avatar.url, class: "post-user-avatar" %>
<div class="post-info">
	<p class="post-author"><%= link_to @user.fname + " " + @user.lname, user_path(@user) %></p>
	<p class="post-created"><%= post.created_at.strftime("%b. %d, %Y") %> at <%= post.created_at.strftime("%l:%m %p") %></p>
</div>

<li class="user_post_body"><%= post.body_html %></li>
<li class="user_post_tag"><%= link_to post.tag, users_path %></li>

<% if post.image_file_name == nil %>
	<div></div>
<% else %>
	<li class="user_post_image"><%= image_tag post.image.url, class: "post-image" %></li>
<% end %>

<li class="edit_user_post">
	<% if current_user and @user == current_user %>
		<%= link_to 'Edit Post', edit_post_path(post) %> |
	<% end %>
	<%= link_to 'Comment', post_path(post) %>
	<div class="comments-list">
	</div>
</li>
<hr class="post_divider_hr"/>

app/views/users/_post_form.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
	<%=f.text_area :body, placeholder: "Update your status...", :class => "post_body form-control" %>
	<%=f.text_field :tag, placeholder: "#add tags to your post (i.e. #running, #yoga)", :class => "post_tag form-control" %>
  <p class="btn btn-default add-image-btn">Add Image</p>
  <p class="choose-file-btn"><%=f.file_field :image, :class => "post-image" %></p>
	<%=f.submit 'Post', :class => "btn btn-default postBtn" %>
<% end %>

app/views/users/index.html.erb
<h1 class="title user-show-title"><a href="/"><span id="fit">FIT</span>racker</a></h1>
<div class="user-index-wrapper">
	<div class="following-side-menu">
		<div class="follow">	
			<h4> You are following... </h4>
			<ul>
				<% current_user.followeds.each do |user| %>
					<li><%= image_tag user.avatar.url, class: "follow-avatar" %></li>
					<li><%= link_to user.fname + " " + user.lname, user_path(user) %></li><br>
				<% end %>
			</ul>
		</div>
		<hr class="follow-hr">
		<div class="follow">
			<h4> Your followers... </h4>
			<ul>
				<% current_user.followers.each do |user| %>
					<li><%= image_tag user.avatar.url, class: "follow-avatar" %></li>
					<li><%= link_to user.fname + " " + user.lname, user_path(user) %></li><br>
				<% end %>
			</ul>
		</div>
	</div>	
	<div class="user-feed">
		<% current_user.followeds.each do |user| %>
			<% user.posts.each do |post| %>
				<%= image_tag user.avatar.url, class: "post-user-avatar" %>
				<div class="post-info">
					<p class="post-author"><%= link_to user.fname + " " + user.lname, user_path(user) %></p>
					<p class="post-created"><%= post.created_at.strftime("%b. %d, %Y") %> at <%= post.created_at.strftime("%l:%m %p") %></p>
				</div>
				<div class="user_post_body"><%= post.body_html %></div>
				<div class="user_post_tag"><%= link_to post.tag, users_path %></div>
				<% if post.image_file_name == nil %>
					<div></div>
				<% else %>
					<div class="user_post_image"><%= image_tag post.image.url, class: "post-image" %></div>
				<% end %>
				<br>
				<p class="comment"><%= link_to 'Comment', post_path(post) %></p>
				<hr>
			<% end %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h1 class="title"><a href="/"><span id="fit">FIT</span>racker</a></h1>
<div class="page-wrapper">	
	<div class="user_wrapper">
		<div class="bio-wrapper">
			<%= render 'bio' %>
		</div>

		<div class="user-following-side-menu">
			<%= render 'follow' %>
		</div>	
		
		<div class="user-posts-section">
			<nav class="user-nav">
				<ul>
					<li id="nav-goals"><%= link_to "My Goals", user_goals_user_path(@user) %></li><!--
					--><li class="active" id="nav-posts"><%= link_to "Post Feed", @user %></li><!--
					--><li class="mobile-only"><%= link_to "Follows", user_follows_user_path(@user) %></li>
				</ul>
			</nav>
			<div class="row user_posts">
				<% if current_user and @user == current_user %>
					<%= render 'post_form' %>
				<% end %>
			</div>

			<hr class="post-form-divider">

			<div class="row">
				<ul class="user_posts_list">
					<%= render partial: 'post', collection: @user.posts %>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/users/user_follows.html.erb
<h1 class="title"><a href="/"><span id="fit">FIT</span>racker</a></h1>
<div class="user_wrapper">
	<div class="bio-wrapper">
		<%= render 'bio' %>
	</div>

	<div class="follows">
		<nav class="user-nav">
			<ul>
				<li id="nav-goals"><%= link_to "My Goals", user_goals_user_path(@user) %></li><!--
				--><li id="nav-posts"><%= link_to "Post Feed", @user %></li><!--
				--><li class="mobile-only active"><%= link_to "Follows", user_follows_user_path(@user) %></li>
			</ul>
		</nav>
		<%= render 'follow' %>
	</div>
</div>

app/views/users/user_goals.html.erb
<h1 class="title"><a href="/"><span id="fit">FIT</span>racker</a></h1>
<div class="user_wrapper">
	<div class="bio-wrapper">
		<%= render 'bio' %>
	</div>

	<div class="goals-following-side-menu">
		<%= render 'follow' %>
	</div>

	<div class="row user-goals">
		<nav class="user-nav">
			<ul>
				<li class="active" id="nav-goals"><%= link_to "My Goals", user_goals_user_path(@user) %></li><!--
				--><li id="nav-posts"><%= link_to "Post Feed", @user %></li><!--
				--><li class="mobile-only"><%= link_to "Follows", user_follows_user_path(@user) %></likj>
			</ul>
		</nav>
		<%= render 'goal' %>
	</div>
	
</div>