config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  post 'users/interests', to: 'users#interests'
  post 'users/goals', to: 'users#goals'

  resources :users do
    member do
      post 'follow'
      post 'unfollow'
      get 'user_goals'
      get 'user_follows'
    end
  end

  resources :interests
  resources :goals
  
  resources :posts do
    resources :comments
  end

  root 'home#index'

  get 'explore' => 'home#explore'

end

app/models/interest.rb
class Interest < ActiveRecord::Base
	has_many :user_interests

	validates_presence_of :name
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController

	def new
		@interests = Interest.all	
	end

	def create
		
	end

	def edit
		@user = User.find(params[:id])
		@interests = Interest.all
	end

	def update
		if param_posted?(:interests)
      if @user.interest.update_attributes(params[:interests])
          flash[:notice] = "Changes saved."
          redirect_to user_interests_user_path(@user)
      end
  	end
	end

	def destroy
		
	end

end

app/views/interests/edit.html.erb
	

	<!-- users_interests = @user_interests.map{|interest| interest.name}
	users_interests.include?()
 -->	<div class="interests-wrapper">
		<div class="row interests-form">
			<%= form_tag(users_interests_path, method: :post) do %>
				<ul class="interests-list">
				  <% @interests.each do |interest| %>
				      <li>
				        <%= check_box_tag 'interests[]', interest.id, UserInterest.include  %>
				        <%= interest.name %>
				      </li>
				  <% end %>
				</ul>
				<%= submit_tag "Save Changes", class: "btn btn-default interestsBtn" %>
			<% end %>
		</div>
	</div>
	
</div>

app/views/interests/new.html.erb
<div class="interests-bkimg">
	<div class="interests-copy-wrapper">
		<p class="interests-copy">Now let's build up your profile, <br>please select what you're interested in below!</p>
	</div>
</div>
<div class="interests-wrapper">	

	<div class="interests-form">
		<%= form_tag(users_interests_path, method: :post) do %>
			<ul class="interests-list">
			  <% @interests.each do |interest| %>
			      <li>
			        <%= check_box_tag 'interests[]', interest.id %>
			        <%= interest.name %>
			      </li>
			  <% end %>
				<%= submit_tag "Save", class: "btn btn-default interestsBtn" %>
			</ul>
		<% end %>
	</div>
	
</div>