config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  post 'users/interests', to: 'users#interests'
  post 'users/goals', to: 'users#goals'

  resources :users do
    member do
      post 'follow'
      post 'unfollow'
      get 'user_goals'
      get 'user_follows'
    end
  end

  resources :interests
  resources :goals
  
  resources :posts do
    resources :comments
  end

  root 'home#index'

  get 'explore' => 'home#explore'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	# scope :subscribed, ->(followeds) { where user_id: followeds }

	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
	do_not_validate_attachment_file_type :image

  auto_html_for :body do
    html_escape
    image
    youtube(:width => "100%", :height => 250, :autoplay => false)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def show
		@comment = Comment.new
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@posts = Post.order('created_at ASC')
		if @post.save
			flash[:notice] = "New post!"
			redirect_to current_user
		else
			flash[:notice] = "Something went wrong."
			redirect_to current_user
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			flash[:notice] = "Post updated!"
			redirect_to current_user
		else
			flash[:alert] = "Something went wrong."
			render :edit
		end
	end

	def destroy
		@post.destroy
		flash[:notice] = "Post deleted!"
		redirect_to current_user
	end

	private

	def post_params
		params.require(:post).permit(:body, :image, :video, :tag).merge(user_id: current_user.id)
	end

	def set_post
		@post = Post.find(params[:id])
	end
end

app/views/posts/create.js.erb
$(".user_posts_list").prepend("<%= j render partial: '/users/post', locals: {post: @post} %>")

app/views/posts/edit.html.erb
<h1 class="title"><a href="/"><span id="fit">FIT</span>racker</a></h1>
<div class="row edit_user_posts">
	<h1 class="header edit-post-header">Edit Post</h1>
	<p class="delete-post"><%= link_to 'Cancel', user_path(@post.user) %> | <%= link_to 'Delete Post', post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %></p>
	<%= form_for @post do |f| %>
		<%=f.text_area :body, placeholder: "Update your status...", :class => "post_body form-control" %>
		<%=f.text_field :tag, placeholder: "#add tags to your post (i.e. #running, #yoga)", :class => "post_tag form-control" %>
	  <p class="btn btn-default add-image-btn">Add Image</p>
	  <p class="choose-file-btn"><%=f.file_field :avatar, :class => "post-avatar" %></p>
		<%=f.submit 'Update', :class => "btn btn-default postBtn" %>
	<% end %>
</div>

app/views/posts/show.html.erb
<h1 class="title"><a href="/"><span id="fit">FIT</span>racker</a></h1>
<div class="row show-posts-wrapper">	
	<%= image_tag @post.user.avatar.url, class: "post-user-avatar" %>
	<div class="post-info">
		<p class="post-author"><%= link_to @post.user.fname + " " + @post.user.lname, user_path(@post.user) %></p>
		<p class="post-created"><%= @post.created_at.strftime("%b. %d, %Y") %> at <%= @post.created_at.strftime("%l:%m %p") %></p>
	</div>

	<li class="user_post_body"><%= @post.body_html %></li>
	<li class="user_post_tag"><%= link_to @post.tag, users_path %></li>

	<% if @post.image_file_name == nil %>
		<div></div>
	<% else %>
		<li class="user_post_image"><%= image_tag @post.image.url, class: "post-image" %></li>
	<% end %>

	<li class="edit_user_post">
		<% if current_user and @user == current_user %>
			<%= link_to 'Edit Post', edit_post_path(@post) %>
		<% end %>
	</li>

	<div class="comments-section">
		<ul class="comments-list">
			<% @post.comments.each do |comment| %>
				<%= image_tag comment.user.avatar.url, class: "comment-user-avatar" %>
				<div class="comment-info">
					<p class="comment-author"><%= link_to comment.user.fname + " " + comment.user.lname, user_path(comment.user) %></p>
					<p class="comment-created"><%= comment.created_at.strftime("%B %d") %> at <%= comment.created_at.strftime("%l:%m %p") %></p>
				</div>
				<li class="comment-body"><%= comment.body %></li><br>
				<li class="edit_user_comment"> 
					<% if current_user and comment.user == current_user %>
						<%= link_to 'Edit Comment', edit_post_comment_path(@post, comment) %> | <%= link_to 'Delete', post_comment_path(@post, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } %> 
					<% end %>
				</li>
				<div class="comments-divider"></div>
			<% end %>
		</ul>
	</div>

	<%= form_for ([@post, @comment]) do |f| %>
		<%= f.text_area :body, placeholder: "Add a comment...", :class => "form-control" %>
		<%= f.submit 'Post', class: "post-comment-btn"%>
	<% end %>

</div>