config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  post 'users/interests', to: 'users#interests'
  post 'users/goals', to: 'users#goals'

  resources :users do
    member do
      post 'follow'
      post 'unfollow'
      get 'user_goals'
      get 'user_follows'
    end
  end

  resources :interests
  resources :goals
  
  resources :posts do
    resources :comments
  end

  root 'home#index'

  get 'explore' => 'home#explore'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FITracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  <link href='http://fonts.googleapis.com/css?family=Bowlby+One|Raleway:700,400|Montserrat+Subrayada|Open+Sans' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="javascripts/slidebars.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

</head>
<body>

<% if current_user %>
	<p class="current-username"><%= link_to current_user.fname + " " + current_user.lname, current_user %></p>
<% end %>

<% if current_user %>
	<a href="#"><i class="fa fa-bars fa-2x menu-bars sb-toggle-left"></i></a>

	<div class="sb-slidebar sb-left">
		<nav class="explore-nav">
			<ul>
				<% if current_user %>
					<li><%= link_to "Home", users_path, 'data-no-turbolink' => true %></li>
					<li><%= link_to "Profile", current_user, 'data-no-turbolink' => true %></li>
					<li><%= link_to "Explore", explore_path, 'data-no-turbolink' => true %></li>
					<li></i><%= link_to "Logout", destroy_user_session_path, method: :delete, 'data-no-turbolink' => true %></li>
				<% end %>
			</ul>
		</nav>
	</div>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>